apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: odoo
  region: us-west-2

vpc:
  id: "vpc-67b71b1f"
  subnets:
    private:
      private-one:
          id: "subnet-0a349ce802b42984a"
      private-two:
          id: "subnet-08c53e616a85ae791"

managedNodeGroups:
  - name: ng-arm-odoo
    instanceType: m6g.medium
    desiredCapacity: 2
    privateNetworking: true