---
apiVersion: v1
kind: Namespace
metadata:
  name: odoo

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pvc
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-a481d450

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-storage-claim
  namespace: odoo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: odoo-arm
  namespace: odoo
  labels:
    app: odoo-arm
spec:
  ports:
    - port: 80
      targetPort: 8069
  selector:
    app: odoo-arm
    tier: frontend
#  type: NodePort
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo
data:
  odoo.conf: |-
    [options]
    addons_path = /mnt/extra-addons
    data_dir = /var/lib/odoo
    db_host = odoo.cmq96p5vz1ps.us-east-1.rds.amazonaws.com
    db_port = 5432
    db_name = odoo
    db_user = odoo
    db_password = odoodemo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-arm
  namespace: odoo
  labels:
    app: odoo-arm
spec:
  replicas: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo-arm
  template:
    metadata:
      labels:
        app: odoo-arm
        tier: frontend
    spec:
      containers:
        - image: wujiade/graviton2-psa:v1
          name: odoo-arm
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
          volumeMounts:
          - name: efs-pvc
            mountPath: /var/lib/odoo
          - name: config-volume
            mountPath: "/etc/odoo/"
      volumes:
      - name: efs-pvc
        persistentVolumeClaim:
          claimName: efs-storage-claim
      - name: config-volume
        configMap:
          name: odoo-config
      nodeSelector:
        kubernetes.io/arch: arm64
